config/routes.rb
TimeTracker::Application.routes.draw do

  resources :time_entries

  resources :tasks

  resources :projects

  resources :clients

  resources :accounts 

  root :to => 'home#index'
  devise_for :users do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  description      :text
#  estimated_budget :float
#  hourly_rate      :float
#  estimated_hour   :float
#  start_date       :datetime
#  end_date         :datetime
#  manager_id       :integer
#  client_id        :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :client
  belongs_to :manager,:class_name => "User",:foreign_key => "manager_id"
  validates :name, :manager_id, :client_id, :presence => true
  #validate :start_and_end_date_range

  def account
    self.client.account
  end

  private
  def start_and_end_date_range
    errors.add(:start_date, "can't be greater then end date") if (self.start_date.present? && self.end_date.present?) && self.start_date > self.end_date
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = @account.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = @account.projects.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = @account.projects.new
    @users = @account.users
    @clients = @account.clients
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = @account.projects.find(params[:id])
    @users = @account.users
    @clients = @account.clients
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = @account.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = @account.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = @account.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project,:html=>{:class=>"data-form"}) do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this time_entry from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :estimated_budget
    = f.text_field :estimated_budget
  .field
    = f.label :hourly_rate
    = f.text_field :hourly_rate
  
  .field
    = f.label :estimated_hour
    = f.text_field :estimated_hour
  .field
    = f.label :start_date
    = f.text_field :start_date, :class=>"datepicker", :readonly  => true
  .field
    = f.label :end_date
    = f.text_field :end_date, :class=>"datepicker", :readonly  => true
  .field
    = f.label :manager_id
    = collection_select(:project, :manager_id, @users, :id, :email, {:prompt => 'Please select manager for the project'})
    .clear
  .field
    = f.label :client_id
    = collection_select(:project, :client_id, @clients, :id, :name, {:prompt => 'Please select client for the project'})
    .clear

  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing Projects
= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing Projects
.field
  .clear
%table.listing
  %tr
    %th Name
    %th Description
    %th Estimated budget
    %th Hourly rate
    %th Estimated hour
    %th Start Date
    %th End Date
    %th Manager
    %th Client
    %th
    %th{:width=>"40px"}
    

  - @projects.each do |project|
    %tr
      %td= link_to project.name,project
      %td= project.description
      %td= project.estimated_budget
      %td= project.hourly_rate
      %td= project.estimated_hour
      %td= project.start_date
      %td= project.end_date
      %td= project.manager.try(:email)
      %td= project.client.try(:name)
      %td= link_to 'Add Task', new_task_path(:project => project)
      %td.edit_link 
        = link_to image_tag('edit_10.png',:border => 0), edit_project_path(project)
        = link_to image_tag('delete_10.png',:border => 0), project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New Project
.field
  .clear

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path