config/routes.rb
TimeTracker::Application.routes.draw do

  resources :time_entries

  resources :tasks

  resources :projects

  resources :clients

  resources :accounts 

  root :to => 'home#index'
  devise_for :users do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  # GET /time_entries
  # GET /time_entries.json
  def index
    @time_entries = TimeEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_entries }
    end
  end

  # GET /time_entries/1
  # GET /time_entries/1.json
  def show
    @time_entry = TimeEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_entry }
    end
  end

  # GET /time_entries/new
  # GET /time_entries/new.json
  def new
    @time_entry = TimeEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_entry }
    end
  end

  # GET /time_entries/1/edit
  def edit
    @time_entry = TimeEntry.find(params[:id])
  end

  # POST /time_entries
  # POST /time_entries.json
  def create
    @time_entry = TimeEntry.new(params[:time_entry])

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully created.' }
        format.json { render json: @time_entry, status: :created, location: @time_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_entries/1
  # PUT /time_entries/1.json
  def update
    @time_entry = TimeEntry.find(params[:id])

    respond_to do |format|
      if @time_entry.update_attributes(params[:time_entry])
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_entries/1
  # DELETE /time_entries/1.json
  def destroy
    @time_entry = TimeEntry.find(params[:id])
    @time_entry.destroy

    respond_to do |format|
      format.html { redirect_to time_entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/time_entries/_form.html.haml
= form_for @time_entry do |f|
  -if @time_entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@time_entry.errors.count, "error")} prohibited this time_entry from being saved:"
      %ul
        - @time_entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_time
    = f.text_field :start_time
  .field
    = f.label :end_time
    = f.text_field :end_time
  .field
    = f.label :created_date
    = f.datetime_select :created_date
  .field
    = f.label :task_id
    = f.number_field :task_id
  .actions
    = f.submit 'Save'

app/views/time_entries/edit.html.haml
%h1 Editing time_entry

= render 'form'

= link_to 'Show', @time_entry
\|
= link_to 'Back', time_entries_path

app/views/time_entries/index.html.haml
%h1 Listing time_entries

%table
  %tr
    %th Name
    %th Start time
    %th End time
    %th Created date
    %th Task
    %th
    %th
    %th

  - @time_entries.each do |time_entry|
    %tr
      %td= time_entry.name
      %td= time_entry.start_time
      %td= time_entry.end_time
      %td= time_entry.created_date
      %td= time_entry.task_id
      %td= link_to 'Show', time_entry
      %td= link_to 'Edit', edit_time_entry_path(time_entry)
      %td= link_to 'Destroy', time_entry, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Time entry', new_time_entry_path

app/views/time_entries/new.html.haml
%h1 New time_entry

= render 'form'

= link_to 'Back', time_entries_path

app/views/time_entries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @time_entry.name
%p
  %b Start time:
  = @time_entry.start_time
%p
  %b End time:
  = @time_entry.end_time
%p
  %b Created date:
  = @time_entry.created_date
%p
  %b Task:
  = @time_entry.task_id

= link_to 'Edit', edit_time_entry_path(@time_entry)
\|
= link_to 'Back', time_entries_path