config/routes.rb
TimeTracker::Application.routes.draw do

  resources :time_entries

  resources :tasks

  resources :projects

  resources :clients

  resources :accounts 

  root :to => 'home#index'
  devise_for :users do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TimeTracker
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    
    = csrf_meta_tags
  %body
    .wrapper.container_16
      .header
        .login
          %ul
            - if current_user
              %li
                Logged in as #{current_user.full_name}
              %li= link_to "Log out", logout_path
            - else
              %li
                = link_to "Sign up", new_account_path
              |
              %li= link_to "log in", login_path
        .menu-bar
          %ul.active_class
            %li
              = link_to "Home", root_path,:class=>current_class("home")
            - if current_user
              %li
                =# link_to "Account", account_path(current_user.account),:class=>current_class("users")
              %li
                = link_to "Account", accounts_path,:class=>current_class("accounts")
                = link_to "Client", clients_path,:class=>current_class("clients")
                = link_to "Project", projects_path,:class=>current_class("projects")
                = link_to "Task", tasks_path,:class=>current_class("tasks")
            -else
              %li
                = link_to "Sign up", new_account_path,:class=>current_class("users")
        .active-line1
      .content.grid_16
        %div{:class => "main-content #{main_content_css_class}"}
          %p.notice= notice
          %p.alert= alert
          = yield
        %div{:class => "sidebar #{sidebar_css_class}"}
          = yield :sidebar
      = clearing_span
      .push
    .container_16.footer
      Footer